### ISSUE TITLE
The remote server returned an error: (500) Internal Server Error.

### ISSUE THREAD

**Issue by yingyi666** [JaimeZeng/scoop-apps#65]
在安装
![image](https://user-images.githubusercontent.com/41784264/148508123-41c58ace-c069-4260-ad26-70ebd5af5b85.png)
时，出现以下错误：

```bash
The remote server returned an error: (500) Internal Server Error.
URL https://pan.jiemi.workers.dev/?file=/Public/scoop/Music/QQMusic_v18.44_NoAD_Portable.7z is not valid
```

同时我也自己尝试访问了上面的URI，结果是错误的

**Comment by JaimeZeng** [comment]
我的锅，今早重新部署了 onedindex 更换了地址，忘记替换仓库的地址了......

**Comment by JaimeZeng** [comment]
![image](https://user-images.githubusercontent.com/78083448/148546795-a48f271a-015a-4138-a700-31bc1b41fdc9.png)

已更新😂
