### ISSUE TITLE
install fail

### ISSUE THREAD

**Issue by chriscp-cat** [JaimeZeng/scoop-apps#71]
```
PS C:\Users\chris> scoop install sapps/bandizip
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'bandizip' (7.23) [64bit]
Loading BANDIZIP-SETUP-STD-ALL-PATCH_7.23.7z from cache.
Checking hash of BANDIZIP-SETUP-STD-ALL-PATCH_7.23.7z ... ok.
Running pre-install script...
7z:
Line |
   2 |  7z x -p2022 $dir\$7z $('-o' + $dir) | Out-Null
     |  ~~
     | The term '7z' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

之前是会安装7z依赖的 现在貌似不会了  不知道算不算是bug

**Comment by chriscp-cat** [comment]
顺便问一下 便携版bandizip是无法使用 快速拖放功能吗

**Comment by JaimeZeng** [comment]
这个你试一下安装 `7zip` 包看能不能解决

**Comment by chriscp-cat** [comment]
已经安装好了 只是反馈一下

**Comment by JaimeZeng** [comment]
> 顺便问一下 便携版bandizip是无法使用 快速拖放功能吗

这个  **快速拖放** 是什么意思？没明白...

**Comment by chriscp-cat** [comment]
就是bandizip独有功能  在设置里打开的   直接解压到目标目录 不需要通过系统从临时目录复制过去

**Comment by chriscp-cat** [comment]
xftp和xshell安装也没法用 缺少注册表信息

**Comment by JaimeZeng** [comment]
> 就是bandizip独有功能 在设置里打开的 直接解压到目标目录 不需要通过系统从临时目录复制过去

看了一下好像是便携版不能使用这个功能

![image](https://user-images.githubusercontent.com/78083448/148978852-46237e5e-b7a5-4875-ab8b-aca0865eaa21.png)

**Comment by JaimeZeng** [comment]
> xftp和xshell安装也没法用 缺少注册表信息

xshell 和 xftp 我就一直在用，怎么可能用不了呢

![image](https://user-images.githubusercontent.com/78083448/148979602-e0d2dd6e-6bc4-4747-b5e0-dacd13ded488.png)

**Comment by chriscp-cat** [comment]
![image](https://user-images.githubusercontent.com/68489543/148980155-cbe5c637-ca17-4e1c-b75e-78e28cee56a7.png)
我觉得是之前安装过安装版的原因

**Comment by JaimeZeng** [comment]
这个库里的PJ软件我只是从 423down.com， qiuquan.cc， ghxi.com 网站下载直接上传 onedrive，其他从未改动。而且仓库里95% 的软件我都在使用，本地测试没问题才推送到 github 的

**Comment by JaimeZeng** [comment]
12点半了，早点睡吧，晚安~
